name: Conventional Commitlint

on:
  push:
    branches: ['main']
    paths-ignore:
      - "documents/**/images/**"
  pull_request:
    paths-ignore:
      - "documents/**/images/**"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Conventional Commitlint
    steps:
      - name: Conventional Commitlint
        uses: opensource-nepal/commitlint@v1