name: Release and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.semantic-release.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run semantic release
        id: semantic-release
        uses: go-semantic-release/action@v1.24.1
        with:
          github-token: ${{ secrets.PAT }}
          allow-initial-development-versions: true

      - name: Output the new version
        run: echo "New version is ${{ steps.semantic-release.outputs.version }}"
  
  docker:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image to GHCR
        run: |
          VERSION=${{ needs.release.outputs.next_version }}
          IMAGE=ghcr.io/${{ github.repository_owner }}/tranzr-moves-services 

          docker build -f Src/TranzrMoves.Api/Dockerfile -t $IMAGE:$VERSION .
          docker tag $IMAGE:$VERSION $IMAGE:latest

          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest